- name: Download DEB file
  get_url:
    url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v{{ RABBITMQ_VERSION | replace('.','_') }}/rabbitmq-server_{{ RABBITMQ_VERSION }}-1_all.deb"
    dest: /tmp
- name: install rabbitmq
  apt:
    state: present
    deb: "/tmp/rabbitmq-server_{{ RABBITMQ_VERSION }}-1_all.deb"
- name: start rabbitmq server
  service:
    name: rabbitmq-server
    state: started
    enabled: true
