- name: Download RPM file
  get_url:
    url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v{{ RABBITMQ_VERSION | replace('.','_') }}/rabbitmq-server-{{ RABBITMQ_VERSION }}-1.el7.noarch.rpm"
    dest: /tmp
- name: install rabbitmq
  yum:
    state: present
    name: "/tmp/rabbitmq-server-{{ RABBITMQ_VERSION }}-1.el7.noarch.rpm"
- name: start rabbitmq server
  service:
    name: rabbitmq-server
    state: started
    enabled: true
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
- name: Install pip
  yum:
    name: python-pip
    state: present
- name: Install requests package
  pip:
    name: requests
    state: present
